import { spawnSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

interface ContributorConfigEntry {
  displayName: string;
  emails: string[];
  login?: string;
  note?: string;
  url?: string;
}

interface ContributorsConfig {
  ignoredEmails?: string[];
  ignoredLogins?: string[];
  contributors?: ContributorConfigEntry[];
}

interface GitAuthor {
  name: string;
  email: string;
}

interface Contributor {
  displayName: string;
  login?: string;
  note?: string;
  url?: string;
}

const configPath = resolve('contributors.config.json');
const markdownPath = resolve('CONTRIBUTORS.md');
const appDataPath = resolve('src/data/contributors.ts');
const readmePath = resolve('README.md');

function extractGithubLogin(name: string, email: string) {
  const noreplyMatch = email.match(/^\d+\+(.+)@users\.noreply\.github\.com$/);

  if (noreplyMatch) {
    return noreplyMatch[1];
  }

  return name.includes('[bot]') ? name : null;
}

function getGitAuthors(): GitAuthor[] {
  const result = spawnSync('git', ['log', '--format=%aN%x09%aE'], {
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    throw result.error ?? new Error(result.stderr);
  }

  const output = result.stdout;

  return output
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const [name, email] = line.split('\t');
      if (!name || !email) {
        throw new Error(`Unable to parse git author line: ${line}`);
      }

      return { name, email: email.toLowerCase() };
    });
}

function getContributorOverrides(config: ContributorsConfig) {
  const overrides = new Map<string, ContributorConfigEntry>();

  (config.contributors ?? []).forEach((contributor) => {
    (contributor.emails ?? []).forEach((email) => {
      overrides.set(email.toLowerCase(), contributor);
    });
  });

  return overrides;
}

function contributorKey(contributor: Contributor) {
  return (
    contributor.login?.toLowerCase() ?? contributor.displayName.toLowerCase()
  );
}

function normalizeContributor(
  author: GitAuthor,
  overrides: Map<string, ContributorConfigEntry>,
): Contributor {
  const override = overrides.get(author.email) ?? {};
  const inferredLogin = extractGithubLogin(author.name, author.email);
  const login = override.login ?? inferredLogin;
  const displayName = override.displayName ?? login ?? author.name;

  return {
    displayName,
    login,
    note: override.note,
    url: override.url ?? (login ? `https://github.com/${login}` : undefined),
  };
}

function sortContributors(contributors: Contributor[]) {
  return contributors.sort((a, b) =>
    a.displayName.localeCompare(b.displayName, undefined, {
      numeric: true,
      sensitivity: 'base',
    }),
  );
}

function buildContributors(authors: GitAuthor[], config: ContributorsConfig) {
  const overrides = getContributorOverrides(config);
  const ignoredLogins = new Set(
    (config.ignoredLogins ?? []).map((login) => login.toLowerCase()),
  );
  const ignoredEmails = new Set(
    (config.ignoredEmails ?? []).map((email) => email.toLowerCase()),
  );
  const contributors = new Map<string, Contributor>();

  authors.forEach((author) => {
    if (ignoredEmails.has(author.email)) {
      return;
    }

    const contributor = normalizeContributor(author, overrides);
    if (
      contributor.login &&
      ignoredLogins.has(contributor.login.toLowerCase())
    ) {
      return;
    }

    const key = contributorKey(contributor);
    const existing = contributors.get(key);

    contributors.set(key, {
      ...existing,
      ...contributor,
      note: contributor.note ?? existing?.note,
      url: contributor.url ?? existing?.url,
    });
  });

  return sortContributors([...contributors.values()]);
}

function renderMarkdown(contributors: Contributor[]) {
  const lines = [
    '# Contributors',
    '',
    '<!-- This file is generated by npm run update-contributors. -->',
    '',
    ...contributors.map((contributor) => {
      const name = contributor.url
        ? `[${contributor.displayName}](${contributor.url})`
        : contributor.displayName;
      const note = contributor.note ? ` - ${contributor.note}` : '';

      return `- ${name}${note}`;
    }),
    '',
  ];

  return lines.join('\n');
}

function renderAppData(contributors: Contributor[]) {
  return `// This file is generated by npm run update-contributors.

export interface Contributor {
  displayName: string;
  login?: string;
  note?: string;
  url?: string;
}

export const CONTRIBUTORS: Contributor[] = ${JSON.stringify(contributors, null, 2)};
`;
}

function renderReadmeContributors(contributors: Contributor[]) {
  return contributors
    .map((contributor) => {
      const handle = contributor.login
        ? `@${contributor.login}`
        : contributor.displayName;
      const name = contributor.url ? `[${handle}](${contributor.url})` : handle;
      const note = contributor.note ? ` - ${contributor.note}` : '';

      return `- ${name}${note}`;
    })
    .join('\n');
}

async function main() {
  const config = JSON.parse(
    await readFile(configPath, 'utf8'),
  ) as ContributorsConfig;
  const contributors = buildContributors(getGitAuthors(), config);

  await writeFile(markdownPath, renderMarkdown(contributors));
  await writeFile(appDataPath, renderAppData(contributors));

  const readmeContent = await readFile(readmePath, 'utf8');
  const readmeContributorsList = renderReadmeContributors(contributors);
  const readmeRegex = /(## Contributors\n+)([\s\S]*?)(\n+(?=## |$))/;
  const newReadmeContent = readmeContent.replace(
    readmeRegex,
    (_match, p1, _p2, p3) => p1 + readmeContributorsList + p3,
  );
  await writeFile(readmePath, newReadmeContent);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
