// This file is generated by bun run update-contributors.

export interface Contributor {
  displayName: string;
  login?: string;
  note?: string;
  url?: string;
}

export const CONTRIBUTORS: Contributor[] = [
  {
    displayName: 'afreetoplaynoob',
    login: 'afreetoplaynoob',
    url: 'https://github.com/afreetoplaynoob',
  },
  {
    displayName: 'Araraura',
    login: 'Araraura',
    url: 'https://github.com/Araraura',
  },
  {
    displayName: 'jjezewski',
    login: 'jjezewski',
    note: 'creator & maintainer',
    url: 'https://github.com/jjezewski',
  },
  {
    displayName: 'KrisGra',
    login: 'krisgrant',
    url: 'https://github.com/krisgrant',
  },
  {
    displayName: 'Matojeje',
    login: 'Matojeje',
    url: 'https://github.com/Matojeje',
  },
  {
    displayName: 'MiaouKING',
    login: 'MiaouKING',
    url: 'https://github.com/MiaouKING',
  },
  {
    displayName: 'newhajinyoon',
    login: 'newhajinyoon',
    url: 'https://github.com/newhajinyoon',
  },
  {
    displayName: 'soulware1',
    login: 'soulware1',
    url: 'https://github.com/soulware1',
  },
  {
    displayName: 'wryyyong',
    login: 'wryyyong',
    url: 'https://github.com/wryyyong',
  },
  {
    displayName: 'xanderrock98',
    login: 'xanderrock98',
    url: 'https://github.com/xanderrock98',
  },
];
