name: Deploy to Cloudflare Pages (Production)

on:
  push:
    tags: ['*.*.*']

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    env:
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_PROJECT: tenna
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_DIR: dist
      PREVIEW_BRANCH: main

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.16.0
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: deploy production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: >
            pages deploy ${{ env.BUILD_DIR }}
            --project-name=${{ env.CF_PROJECT }}
            --branch=${{ env.PREVIEW_BRANCH }}
